sudo: false
language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew check junitPlatformJacocoReport
after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/reports/jacoco/junitPlatformJacocoReport/junitPlatformJacocoReport.xml
